### ISSUE TITLE
Steve ff+2

### ISSUE THREAD

**Issue by eatsports** [roguelike2d/TekkenBot#7] opened 2017-06-30 18:22 UTC
Steve's ff+2 shows as -27 on block for some reason.
Maybe there are other moves like that but i only noticed that one at the moment

**Comment by roguelike2d** [comment] 2017-06-30 21:31
Fixed in the next release. However...

This is caused by Steve's ff+2 having a split recovery, like Lili's d/b+4 ankle breaker animation. Unlike ankle breakers however, the startup time for Steve's ff+2 doesn't need to be subtracted. Currently, the two can be differentiated by the change in the number of recovery frames.

But if additional moves exist that act like this, this issue may have to be reopened either to get the breakpoint right or to completely redo how split recovery moves are displayed.

**Closed by roguelike2d** 2017-06-30 21:31 UTC
